# docker-compose for UI development
version: '3'
services:
  store:
    image: "registry.hub.docker.com/channikhabra/hot-store:0.0.1"
    volumes:
      - ./docker-volumes/store:/var/lib/postgresql/data
      - ./store/migrations:/migrations
    environment:
      POSTGRES_USER: hot
      POSTGRES_PASSWORD: hot
      POSTGRES_DB: hot

  gateway:
    image: "registry.hub.docker.com/channikhabra/hot-gateway:0.0.1"
    ports:
      - "5000:80"
    volumes:
      - ./gateway/gateway.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - docs
      - pms
      - ei
      - pgadmin
      - ui

  docs:
    image: hot-docs
    build: ./docs
    volumes:
      - ./docs:/app
    environment:
      HOST: '0.0.0.0'
      PORT: 80
      BASE_URL: "http://localhost:5000/docs/"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: hot@hot.com
      PGADMIN_DEFAULT_PASSWORD: hot
    depends_on:
      - store

  ei:
    image: "registry.hub.docker.com/channikhabra/hot-ei:0.0.1"
    environment:
      ROARR_LOG: "true"
      HOST: "0.0.0.0"
      PORT: "80"
    depends_on:
      - store

  ui:
    image: ui
    build: ./ui
    environment:
      PORT: 80
      REACT_APP_EI_URL: "http://localhost:5000/ei"
      REACT_APP_PMS_URL: "http://localhost:5000/pms"
      REACT_APP_IAM_URL: "http://localhost:7000"
    volumes:
      - ./ui:/app
      - ./ui/node_modules:/app/node_modules
    command: yarn start

  pms:
    image: "registry.hub.docker.com/channikhabra/hot-pms:0.0.1"
    environment:
      DB_USERNAME: "hot"
      DB_PASSWORD: "hot"
      DB_NAME: "hot"
      DB_HOST: "store"
      DB_PORT: "5432"
      HOST: "0.0.0.0"
      PORT: "80"
      API_PREFIX: "/pms"
    depends_on:
      - store
