version: '3'
services:
  store:
    build: ./store
    ports:
      - 5432:5432
    volumes:
      - ./docker-volumes/store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hot
      POSTGRES_PASSWORD: hot
      POSTGRES_DB: hot
    command: ["postgres", "-c", "log_statement=all"]

  gateway:
    image: hot-gateway
    build: ./gateway
    volumes:
      - ./gateway/gateway.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5000:80
    depends_on:
      - docs
      - pgadmin
      - ui

  docs:
    image: hot-docs
    build: ./docs
    volumes:
      - ./docs:/app
    environment:
      HOST: '0.0.0.0'
      PORT: 80
      BASE_URL: "http://localhost:5000/docs/"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: hot@hot.com
      PGADMIN_DEFAULT_PASSWORD: hot
    depends_on:
      - store

  ui:
    image: ui
    build: ./ui
    environment:
      PORT: 80
      REACT_APP_CORE_API_URL: "http://localhost:5000/api"
    volumes:
      - ./ui/node_modules:/app/node_modules
      - ./ui:/app
    command: yarn start

  core:
    build:
      context: ./hot-core
      dockerfile: Dockerfile
    environment:
      DB_URL: '"postgresql://hot:hot@store/hot"'
      PORT: "80"
    depends_on:
      - store
    volumes:
      - ./hot-core/build:/app
      - ./hot-core/migrations:/app/migrations
      - ./hot-core/jwt-keys.pem:/app/jwt-keys.pem
      - ./hot-core/config.dhall:/app/config.dhall
