version: '3'
services:
  docs:
    image: hot-docs
    build: ./docs
    volumes:
      - ./docs:/app
    ports:
     - 3000:3000

  store:
    image: hot-store
    build: ./store
    volumes:
      - ./docker-volumes/store:/var/lib/postgresql/data
      - ./store/migrations:/migrations
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hot
      POSTGRES_PASSWORD: hot
      POSTGRES_DB: hot

  mbus:
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/hot/redis:/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: hot@hot.com
      PGADMIN_DEFAULT_PASSWORD: hot
    logging:
      driver: none
    ports:
      - 3001:80

  ei:
    image: hot-ei:latest
    build: ./ei
    environment:
      PORT: 80
      ROARR_LOG: 'true'
    volumes:
      - ./ei:/app
      - ./ei/node_modules:/app/node_modules
    command: yarn start:dev
    ports:
     - 3002:80
