version: '3'
services:
  store:
    image: hot-store
    build: ./store
    volumes:
      - ./docker-volumes/store:/var/lib/postgresql/data
      - ./store/migrations:/migrations
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hot
      POSTGRES_PASSWORD: hot
      POSTGRES_DB: hot

  mbus:
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/hot/redis:/data

  docs:
    image: hot-docs
    build: ./docs
    volumes:
      - ./docs:/app
    ports:
     - 7000:3000

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: hot@hot.com
      PGADMIN_DEFAULT_PASSWORD: hot
    logging:
      driver: none
    volumes:
      - ./docker-volumes/pgadmin:/var/lib/pgadmin
    ports:
      - 7001:80

  ei:
    image: hot-ei:latest
    build: ./ei
    environment:
      PORT: 80
      ROARR_LOG: 'true'
    volumes:
      - ./ei:/app
      - ./ei/node_modules:/app/node_modules
    command: yarn start:dev
    ports:
     - 7002:80

  standup-ui:
    image: standup-ui:latest
    build: ./standup-ui
    environment:
      PORT: 80
    volumes:
      - ./standup-ui:/app
      - ./standup-ui/node_modules:/app/node_modules
    command: yarn start
    ports:
     - 7003:80
