version: '3'
services:
  docs:
    image: hot-docs
    build: ./docs
    volumes:
      - ./docs:/app
    ports:
     - 3000:80

  store:
    image: hot-store
    build: ./store
    volumes:
      - ./docker-volumes/store:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hot
      POSTGRES_PASSWORD: hot
      POSTGRES_DB: hot

  mbus:
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/hot/redis:/data

  # hotsidecar:
  #   image: hotsidecar:latest
  #   build: ./sidecar
  #   volumes:
  #     - ./sidecar:/app
  #     - ./sidecar/node_modules:/app/node_modules
  #   command: npm run start:dev
