version: '3'
services:
  docs:
    image: hot-docs
    build: ./docs
    volumes:
      - ./docs:/app
    ports:
     - 3000:80

  store:
    image: hot-store
    build: ./store
    volumes:
      - ./docker-volumes/store:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hot
      POSTGRES_PASSWORD: hot
      POSTGRES_DB: hot

  mbus:
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/hot/redis:/data

  ei:
    image: hot-ei:latest
    build: ./ei
    environment:
      PORT: 80
    volumes:
      - ./ei:/app
      - ./ei/node_modules:/app/node_modules
    command: yarn start:dev
    ports:
     - 3001:80
