- name: Log in to docker registry
  docker_login:
    registry: "{{ ui_docker_registry }}"
    username: "{{ ui_docker_registry_username }}"
    password: "{{ ui_docker_registry_password }}"
  when: ui_docker_registry|default('') != ''

- name: Create docker image
  docker_image:
    name: "{{ ui_docker_name }}"
    tag: "{{ ui_docker_tag }}"
    source: build
    debug: yes
    build:
      path: "{{ ui_src_dir }}"
      dockerfile: "{{ ui_dockerfile }}"
      args:
        PUBLIC_URL: "{{ ui_public_url }}"
        REACT_APP_EI_URL: "{{ ui_ei_url }}"
        REACT_APP_CORE_API_URL: "{{ ui_core_url }}"
        REACT_APP_BASE_PATH: "{{ ui_base_path }}"
      pull: no
    state: present
    repository: "{{ ui_docker_repository }}"
    push: "{{ ui_docker_repository != '' }}"

- name: Destroy docker image
  docker_image:
    state: absent
    name: "{{ ui_docker_name }}"
    tag: "{{ ui_version }}"
  tags: [ never, destroy ]
