FROM node:12-alpine as builder

WORKDIR /app

ENV NODE_ENV=development

COPY . /app

RUN yarn
RUN yarn build

from node:12-alpine

WORKDIR /app

ENV HOST=0.0.0.0
ENV PORT=80
ENV NODE_ENV=production

COPY --from=builder /app/dist /app/dist
COPY package.json /app/

RUN yarn

CMD yarn start
