- name: Log in to docker registry
  docker_login:
    registry: "{{ docs_docker_registry }}"
    username: "{{ docs_docker_registry_username }}"
    password: "{{ docs_docker_registry_password }}"
  when: docs_docker_registry|default('') != ''

- name: Create docker image
  docker_image:
    name: "{{ docs_docker_name }}"
    tag: "{{ docs_docker_tag }}"
    source: build
    debug: yes
    build:
      path: "{{ docs_src_dir }}"
      dockerfile: "{{ docs_dockerfile }}"
      pull: no
      rm: no
    state: present
    repository: "{{ docs_docker_repository }}"
    push: "{{ docs_docker_repository != '' }}"

- name: Destroy docker image
  docker_image:
    state: absent
    name: "{{ docs_docker_name }}"
    tag: "{{ docs_version }}"
  tags: [ never, destroy ]
