FROM node:12-alpine as builder

WORKDIR /app

ENV HOST=0.0.0.0
ENV NODE_ENV=production

RUN npm i -g yarn

COPY ./package.json /app/
COPY ./yarn.lock /app/
RUN yarn

EXPOSE 80

COPY . /app

CMD yarn build

FROM nginx:alpine
COPY nginx-site.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build/ /app
