# Defaults if not specified in --build-arg
ARG sbt_version=1.3.4
ARG sbt_home=/usr/local/sbt

FROM woahbase/alpine-openjdk11:x86_64 as unzip
ARG sbt_version
ARG sbt_home

# Cleverly placed here for caching reasons
RUN apk add --no-cache --update bash

# Download and extract from archive
RUN mkdir -pv "$sbt_home"
RUN wget -qO - "https://github.com/sbt/sbt/releases/download/v$sbt_version/sbt-$sbt_version.tgz" >/tmp/sbt.tgz
RUN tar xzf /tmp/sbt.tgz -C "$sbt_home" --strip-components=1

# Make a clean image (i.e., without extra packages)
FROM woahbase/alpine-openjdk11:x86_64 as assembly
ARG sbt_home
ARG API_PREFIX=""

# sbt requires bash at run-time.
RUN apk add --no-cache --update bash

COPY --from=unzip $sbt_home $sbt_home
RUN ln -sv "$sbt_home"/bin/sbt /usr/bin/

# This triggers a bunch of useful downloads.
RUN sbt compile

WORKDIR /app

ENV HOST=0.0.0.0
ENV PORT=80
EXPOSE 80

COPY . /app

RUN sbt "server/assembly"

FROM woahbase/alpine-openjdk11:x86_64
COPY --from=assembly /app/server/target/scala-2.12/hot-pms.jar /app/pms.jar

CMD java -jar /app/pms.jar
