- name: Log in to docker registry
  docker_login:
    registry: "{{ store_docker_registry }}"
    username: "{{ store_docker_registry_username }}"
    password: "{{ store_docker_registry_password }}"
  when: store_docker_registry|default('') != ''

- name: Create docker image
  docker_image:
    name: "{{ store_docker_name }}"
    tag: "{{ store_docker_tag }}"
    source: build
    debug: yes
    build:
      path: "{{ store_src_dir }}"
      dockerfile: "{{ store_dockerfile }}"
      pull: no
      rm: no
    state: present
    repository: "{{ store_docker_repository }}"
    push: "{{ store_docker_repository != '' }}"

- name: Destroy docker image
  docker_image:
    state: absent
    name: "{{ store_docker_name }}"
    tag: "{{ store_version }}"
  tags: [ never, destroy ]
