- name: Build the HoT Containers
  hosts: builder
  roles:
    - name: infra
      tags: infra
    - name: gateway
      tags: gateway
    - name: standup-ui
      tags: standup-ui
    - name: ei
      tags: ei
    - name: docs
      tags: docs
    - name: store
      tags: store
    - name: pms
      tags: pms
