FROM channikhabra/hot-docs-builder as builder

WORKDIR /app

ARG BASE_URL

COPY . /app
RUN hugo --baseURL "$BASE_URL" --themesDir /themes --theme learn

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/public /app
CMD sh
