- name: Log in to docker registry
  docker_login:
    registry: "{{ gateway_docker_registry }}"
    username: "{{ gateway_docker_registry_username }}"
    password: "{{ gateway_docker_registry_password }}"
  when: gateway_docker_registry|default('') != ''

- name: Create docker image
  docker_image:
    name: "{{ gateway_docker_name }}"
    tag: "{{ gateway_docker_tag }}"
    source: build
    debug: yes
    build:
      path: "{{ gateway_src_dir }}"
      dockerfile: "{{ gateway_dockerfile }}"
      pull: no
      rm: no
    state: present
    repository: "{{ gateway_docker_repository }}"
    push: "{{ gateway_docker_repository != '' }}"

- name: Destroy docker image
  docker_image:
    state: absent
    name: "{{ gateway_docker_name }}"
    tag: "{{ gateway_version }}"
  tags: [ never, destroy ]
