FROM node:12-alpine as builder

WORKDIR /app

ENV HOST=0.0.0.0
ENV NODE_ENV=production

COPY . /app

ARG PUBLIC_URL
ARG REACT_APP_EI_URL
ARG REACT_APP_CORE_API_URL

ARG REACT_APP_BASE_PATH

RUN yarn && yarn build

FROM alpine
COPY --from=builder /app/build/ /app
